eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 9997
spring:
  application:
    name: consumer-client

# To disable Hystrix in Feign
feign.hystrix.enabled: true
